name: ESLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
    
    - name: Yarn
      run: yarn install

    - name: ESLint
      uses: sibiraj-s/action-eslint@v2.1.1
      with:
        bin-path: ./node_modules/.bin
